
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
 namespace PartCommander
 {
	static class Version
	{
		public const int major = 1;
		public const int minor = 1;
		public const int patch = 5;
		public const int build = 1;
		public const string Number = "1.1.5.1";
		public const string Text = Number + "/L Unofficial";
	}
}
